FROM apache/airflow:2.8.1-python3.11

USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends git \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
USER airflow
# Create a virtual environment for dbt to avoid dependency conflicts with Airflow
RUN python -m venv /opt/airflow/dbt_venv && \
    PIP_USER=false /opt/airflow/dbt_venv/bin/pip install --no-cache-dir dbt-core dbt-clickhouse
