version: 2

sources:
  - name: facebook_raw
    database: marketing_raw
    tables:
      - name: raw_fb_campaign_overview_report
        description: "Dữ liệu Facebook Campaign Overview"
        tests:
          - dbt_utils.at_least_one: # Kiểm tra xem bảng có dữ liệu không
              column_name: job_id
      - name: raw_fb_campaign_performance_by_age___gender
        columns:
          - name: data
            tests:
              - not_null # Đảm bảo cột JSON không bị trống
      - name: raw_fb_campaign_daily_report
        columns:
          - name: data
            tests:
              - not_null # Đảm bảo cột JSON không bị trống
      - name: raw_fb_location_detailed_report_metrics
        description: "Dữ liệu Facebook Chi tiết theo ngày"
        columns:
          - name: data
            tests:
              - not_null # Đảm bảo cột JSON không bị trống
      - name: raw_fb_ad_daily_report_metrics
        description: "Dữ liệu Facebook Ad Daily Report Metrics"
        columns:
          - name: data
            tests:
              - not_null # Đảm bảo cột JSON không bị trống
      - name: raw_fb_metadata_shared
        description: "Dữ liệu Facebook Ad Metadata"
        columns:
          - name: data
            tests:
              - not_null # Đảm bảo cột JSON không bị trống
      - name: raw_fb_ad_set_daily_report_metrics
        description: "Dữ liệu Facebook Ad Set Daily Report - hiệu suất theo nhóm quảng cáo (ad set) theo ngày"
        columns:
          - name: data
            tests:
              - not_null # Đảm bảo cột JSON không bị trống
      - name: raw_fb_account_daily_report_metrics
        description: "Dữ liệu Facebook Account Daily Report - hiệu suất theo tài khoản theo ngày"
        columns:
          - name: data
            tests:
              - not_null
      - name: raw_fb_age___gender_detailed_report_metrics
        description: "Dữ liệu facebook ad creative breakdown theo tuổi, giới tính"
        columns:
          - name: data
            tests:
              - not_null # Đảm bảo cột JSON không bị trống
